### ISSUE TITLE
ad hoc adjustment for events that occur at the same time

### ISSUE THREAD

**Issue by jomulder** [TilburgNetworkGroup/remify#13]
Hi, the current default setting to set events at the same time in a random order and equally spaced intervals will result in arbitrary bias and is also not needed. Instead, this should be incorporated in the likelihood which is fairly straightforward. In the case of D dyads, the likelihood of an event would then be

Prod_{d=1}^D lambda(d)^y_d * exp(- waiting time * lambda(d) ),

where lambda(d) is the rate of that event for dyad d and y_d is 1 if dyad d was observed for this event, and 0 elsewhere. This is a simple generalization of the standard case where only one dyad has a y_d that is 1, and now more dyads can be 1. Please check to be sure of course.
Best,
Joris

**Comment by jupepis** [comment]
I close this issue because the suggestion is going to be integrated into the new version of the package (`remify 3.0.0`) and the modeling aspect that is explained here will also be integrated by `remstats` in its future version.
