### ISSUE TITLE
suggestion for plot.reh

### ISSUE THREAD

**Issue by jomulder** [TilburgNetworkGroup/remify#16]
Hi, this is just a reminder that it would be good to have a function that plots a reh object. Maybe it would be useful to give a X by Y panel with the observed event times, a histogram of the waiting times, an aggregated network plot where the thickness is related to the number of events for a tie, a plot of the number of send messages per actor, a plot of the number of received messages per actor, and ???

-- other suggestion --

Maybe create a polt.reh function that shows a grid of frequencies of row (sender) by column (receiver), and barplots in the row and column dimension showing the frequencies of actors as sender and receiver. Maybe reorder the actors depending on their 'activity'. The plot should be sufficient quality that it can be directly copied to a paper (e.g., abiding APA style).

**Comment by jupepis** [comment]
An update of the `plot.remify()`method will be available with `remify 3.1.0`.
