### ISSUE TITLE
edgelist for a model="actor"

### ISSUE THREAD

**Issue by jomulder** [TilburgNetworkGroup/remify#17]
When model="actor", then the egdelist in the resulting reh object still shows the dyad indices. This feels a bit counterintuitive when model="actor" is chosen because then we are not modeling those dyad (indices). Optionally, the edgelist element could also contain a column for actor1 and actor2; this would then be useful regardless of whether a "tie" model or an "actor" model was chosen.

**Comment by jupepis** [comment]
Thanks for the suggestion!  

I close this issue because the suggestion is going to be integrated into the new version of the package (`remify 3.0.0`)
