### ISSUE TITLE
Suggestion for plot.reh

### ISSUE THREAD

**Issue by jomulder** [TilburgNetworkGroup/remify#22]
Maybe create a polt.reh function that shows a grid of frequencies of row (sender) by column (receiver), and barplots in the row and column dimension showing the frequencies of actors as sender and receiver. Maybe reorder the actors depending on their 'activity'. The plot should be sufficient quality that it can be directly copied to a paper (e.g., abiding APA style).

**Comment by jupepis** [comment]
I pasted this suggestion to the issue #16 which is about `plot.reh` and I am closing this issue.
