### ISSUE TITLE
not sure if the 'origin' argument works properly

### ISSUE THREAD

**Issue by jomulder** [TilburgNetworkGroup/remify#26]
I applied the 'reh' function on an edgelist where the 'time' has the 'numeric' class. It added a numeric value to the 'origin' argument but it did not seem to do anything. Could you check if it works in this case. If you want a replicated data example let me know.

**Comment by jupepis** [comment]
You can check  `reh_name$intereventTime[1]` should be equal to `(reh_name$edgelist[1,1]-reh_name$origin)`.

**Comment by jomulder** [comment]
Yes, it works (now). Strange that it did not work yesterday. Thanks!

**Comment by jupepis** [comment]
Great! I close this issue then. 😃
