### ISSUE TITLE
error when plotting (prob caused by a (too) large network of 2500 actors)

### ISSUE THREAD

**Issue by jomulder** [TilburgNetworkGroup/remify#32]
> plot(remify.full)
Hit <Return> to see next plot: 
Hit <Return> to see next plot: 
Error in if (n < 1L) return(character()) : 
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In plot.remify(remify.full) :
  actors are too many for rendering plots with a good quality: the 50 most active actors are selected (descriptives on dyads and actors may differ from the descriptives conducted on the whole set of actors)
2: In max(unique(sort(fill))) :
  no non-missing arguments to max; returning -Inf
3: In hcl.colors(n = max(unique(sort(fill))), palette = palette) :
  NAs introduced by coercion to integer range

> plot(remify.full)
Hit <Return> to see next plot: 
Hit <Return> to see next plot: 
Error in xy.coords(x, y) : 'x' and 'y' lengths differ

Note. It would also be good if the margins & mfrow plotting argument are reset after the plots. Because I get errors, when creating a new plot after this plotting command which is caused by the changed settings/margins.

What is the plot "sender activity per time interval" plotting exactly? How are the "intervals" determined. Maybe we could provide a question how many intervals should be considered when plotting? Maybe we could also leave the plotting for different periods to another function?

A plot of the network (as a network, not a matrix) where the tie thickness correspond with the number of events would be good to add to the list.

**Comment by jupepis** [comment]
Thanks for the feedback and for the suggestions! This function is one that still requires adjustments and checks. I aim anyway to limit some functionalities to smaller networks (e.g., 50 actors maximum) and perhaps meet and discuss some improvements for a future update.

**Comment by jomulder** [comment]
Sounds good.

**Comment by jupepis** [comment]
I close this issue because a new plot function will be available with the next release of `remify 3.2.0`.
