### ISSUE TITLE
Prevent events from getting dropped with missing values in variables that are not used

### ISSUE THREAD

**Issue by mlmeijerink** [TilburgNetworkGroup/remify#37]
`remify()` drops events with missing variables. Currently, if any values on the variables in the edgelist supplied to `remify()` are missing the events are dropped, even when these variables are not meaningful for the analysis. For example, the edgelist in the team4 data has the variable "signal_strength" with missing values, but this variable is not used in the analysis so the events that have missing values on this variable should not be dropped.

Would it be possible to only drop events that have missing values in the "time", "actor1", "actor2", "type" or "weight" variables?

**Comment by jupepis** [comment]
Fixed in remify 3.2.5
